language: python
python:
  - "3.9"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install nose coverage
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python tests/utils/test_pytree.py

after_sucess:
  coveralls